[package]
name = "gy-86-async"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-hal-async = "1.0.0"

[dependencies.nalgebra]
default-features = false
version = "0.32"